baseURL = 'https://blog.janishutz.com/'
languageCode = 'en-us'
title = 'blog.janishutz.com'
theme = 'DoIt'
# post pagination
paginate = "25"
# post excerpt
summaryLength = "10"

[params]
  # DoIt theme version
  version = "0.2.X"
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    themeChangeMode = "switch"
    [params.header.title]
      # URL of the LOGO
      logo = "/images/avatar.png"
      # title name
      name = "blog.janishutz.com"
      pre = ""
      post = ""
      typeit = false
  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2023
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.social]
    RSS = true
    GitHub = 'simplePCBuilding'
  [params.home]
    rss = 10
    [params.home.profile]
      social = true
      enable = true
      avatarLinkURL = "https://janishutz.com"
      title = "<h1>blog.janishutz.com</h1>"
      subtitle = "Technology, Linux, Development"
      avatarURL = "/images/avatar.png"
  [params.page]
    seriesNavigation = true
    lightgallery = true
    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 10
    [params.page.related]
      enable = true
      count = 5


[author]
  name = 'Janis Hutz'
  email = 'development@janishutz.com'
  link = 'https://janishutz.com'
  avatar = '/images/avatar.png'

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "series"
    pre = ""
    post = ""
    name = "Series"
    url = "/series/"
    title = ""
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 10

[related]
  includeNewer = true
  toLower = true
[[related.indices]]
  name = 'series'
  weight = 100

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  # DoIt CHANGED | 0.2.0
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
